sonar.projectKey=samuel-mok-wei-sheng
sonar.sources=.
sonar.host.url=http://host.docker.internal:9000
sonar.token=sqp_fe3af4d9207629858970e875a5f11b1d5f28834e
sonar.exclusions=**/__pycache__/**,web/tests/**,node_modules/**